services:
  principia-aves:
    container_name: principia-aves
    image: ghcr.io/sawbay/principia-aves:latest
    build:
      context: .
    env_file:
      - ./.env
    environment:
      - BOTS_PATH=/app
    ports:
      - "8001:8001"
    volumes:
      - ./bots:/app/bots
      - /var/run/docker.sock:/var/run/docker.sock

  warmbot-01:
    image: ${HUMMINGBOT_IMAGE:-ghcr.io/sawbay/hummingbot:latest}
    container_name: warmbot_1
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      - HEADLESS_MODE=true
      - BROKER_HOST=host.docker.internal
    volumes:
      - ./bots/instances/warmbot_1/conf:/home/hummingbot/conf:rw
      - ./bots/instances/warmbot_1/data:/home/hummingbot/data:rw
      - ./bots/instances/warmbot_1/logs:/home/hummingbot/logs:rw
      - ./bots/scripts:/home/hummingbot/scripts:rw
      - ./bots/controllers:/home/hummingbot/controllers:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"
    tty: true
    stdin_open: true

  warmbot-02:
    image: ${HUMMINGBOT_IMAGE:-ghcr.io/sawbay/hummingbot:latest}
    container_name: warmbot_2
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      - HEADLESS_MODE=true
      - BROKER_HOST=host.docker.internal
    volumes:
      - ./bots/instances/warmbot_2/conf:/home/hummingbot/conf:rw
      - ./bots/instances/warmbot_2/data:/home/hummingbot/data:rw
      - ./bots/instances/warmbot_2/logs:/home/hummingbot/logs:rw
      - ./bots/scripts:/home/hummingbot/scripts:rw
      - ./bots/controllers:/home/hummingbot/controllers:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"
    tty: true
    stdin_open: true

  # warmbot-03:
  #   image: ${HUMMINGBOT_IMAGE:-ghcr.io/sawbay/hummingbot:latest}
  #   container_name: warmbot_3
  #   restart: unless-stopped
  #   network_mode: host
  #   env_file:
  #     - .env
  #   environment:
  #     - HEADLESS_MODE=true
  #     - BROKER_HOST=host.docker.internal
  #   volumes:
  #     - ./bots/instances/warmbot_3/conf:/home/hummingbot/conf:rw
  #     - ./bots/instances/warmbot_3/data:/home/hummingbot/data:rw
  #     - ./bots/instances/warmbot_3/logs:/home/hummingbot/logs:rw
  #     - ./bots/scripts:/home/hummingbot/scripts:rw
  #     - ./bots/controllers:/home/hummingbot/controllers:rw
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 10m
  #       max-file: "5"
  #   tty: true
  #   stdin_open: true
